language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly


before_script:
  - composer install --dev --prefer-source

script:
- vendor/bin/phpunit --coverage-text
